### ISSUE TITLE
docker/build-push-action now supports caching

### ISSUE THREAD

**Issue by mendhak** [jpribyl/action-docker-layer-caching#57]
FWIW, it seems Docker's build-push-action [now supports caching using the Github Cache API](https://docs.docker.com/build/ci/github-actions/cache/#github-cache). Currently it's experimental but seems to work well in the little testing I've done. 

It's just two arguments to the action, [`cache-from` and `cache-to`](https://docs.docker.com/reference/cli/docker/buildx/build/#cache-from). 

```yml
    - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: user/app:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
```

Could be worth a look.
